apiVersion: 1
datasource: 
  - name: Loki
    type: loki
    access: proxy
    orgId: 1
    url: http://loki:3100
    basicAuth: true 
    isDefault: true 
    version: 1
    editable: false 
    
  - name: Prometheus
    type: prometheus 
    url: http://prometheus:9090
    access: proxy 
    isDefault: true 
